project:
  type: website
  output-dir: docs
  resources:
    - "cv_osamura_30012026.pdf"

website:
  title: "Koichi Osamura"
  sidebar: false
  search: false
  navbar:
    logo: ""
    favicon: ""
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - media.qmd
      - teaching.qmd
      - cv.qmd
    right:
      - icon: Linkedin
        href: https://www.linkedin.com/in/koichiosamura
      #- icon: twitter
      #  href: https://twitter.com/koichiosamura
      - text: "{{< iconify fa6-brands:bluesky >}}"
        aria-label: Bluesky
        href: https://bsky.app/profile/koichiosamura.bsky.social
      - text: "{{< iconify fa6-brands:orcid >}}"
        aria-label: Orcid
        href: https://orcid.org/0000-0001-8907-9138
      - icon: github
        href: https://github.com/koichiosamura
      - text: "{{< iconify fa7-solid:building-columns >}}"
        aria-label: University of Vienna
        href: https://ufind.univie.ac.at/en/person.html?id=1004088
    search: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

